name: Daily Contribution Bot

on:
  schedule:
    
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Daily File
        run: |
          
          echo "Last Green Square: $(date)" > update.txt

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add update.txt
          git commit -m "chore: auto-update streak $(date)"
          git push
